name: Backend Notification Service CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v5.3.0
      with:
        context: .
        push: true
        tags: nguyenthuanit265/backend-notification-service:latest

    - name: Transfer Docker image to remote server
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
      
    - name: Run remove docker container backend-notification-service
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_SERVER_USERNAME }}@${{ secrets.REMOTE_EMPLOYER_SERVER_ADDRESS }} << 'ENDSSH'
        docker stop backend-jobstreet-notification-service-prod backend-jobstreet-notification-service-gateway-prod backend-jobstreet-notification-service-server-prod
        docker rm -f backend-jobstreet-notification-service-prod backend-jobstreet-notification-service-gateway-prod backend-jobstreet-notification-service-server-prod
        docker rmi -f nguyenthuanit265/backend-notification-service:latest
        ENDSSH

    - name: Run docker container backend-notification-service
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_SERVER_USERNAME }}@${{ secrets.REMOTE_EMPLOYER_SERVER_ADDRESS }} << 'ENDSSH'
        docker run --name backend-jobstreet-notification-service-server-prod --network jobstreet-network -p 4001:40000 -d nguyenthuanit265/backend-notification-service:latest
        docker run --name backend-jobstreet-notification-service-gateway-prod --network jobstreet-network -p 4002:80 -d nguyenthuanit265/backend-notification-service:latest
        ENDSSH
